spring.application.name=clinicSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/clinicsystem_db
spring.datasource.username=postgres
spring.datasource.password=Ruth123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082